require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
platform :ios, '13.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'VidyoConnector' do
  
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  
  use_native_modules!
end
